name: easy_localization_sheet
description: A tool to help generate json from csv file. It is useful when used with localization packages.
version: 1.0.3
repository: https://github.com/nguyenvanquangqui/easy_localization_sheet

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
   csv: ^5.0.2
   path: ^1.8.3
   yaml: ^3.1.2
   googleapis: ^13.2.0
   googleapis_auth: ^1.6.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3

# easy_localization_sheet test
easy_localization_sheet:
  csv_url: 'https://docs.google.com/spreadsheets/d/1p6oQw6BKObb3RU_fIWskJjofRzEb01cfzfNE14Px4nw/export?format=csv'
  output_dir: 'generated'
  easy_localization_generate: # Optional, remove this block to disable
    output_dir: lib/generated
    output_file_name: locale_keys.g.dart
