name: easy_localization_sheet
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
   csv: ^5.0.1
   path: ^1.8.0
   yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

# easy_localization_sheet test
easy_localization_sheet:
  csv_url: 'https://docs.google.com/spreadsheets/d/1p6oQw6BKObb3RU_fIWskJjofRzEb01cfzfNE14Px4nw/export?format=csv'
  output_dir: 'generated'